
CATEGORIES = [
    "Music", "Rock", "Pop", "Jazz", "Classical Music", "Hip Hop", "Electronic Music", "Country Music", "World Music", "Instrumental",
    "Sports", "Football (Soccer)", "Basketball", "Tennis", "Boxing", "Martial Arts", "Swimming", "Running", "Cycling", "Gym Workouts", "Yoga", "Pilates", "CrossFit", "Hiking", "Climbing",
    "Gaming", "Let’s Play", "Walkthroughs", "Speedruns", "Game Reviews", "eSports", "Mobile Gaming", "Board Games", "Retro Gaming", "VR Gaming",
    "Education", "Math Tutorials", "Physics Lectures", "Chemistry Experiments", "Biology Documentaries", "History Documentaries", "Language Learning", "Programming Tutorials", "Data Science", "AI & Machine Learning", "Astronomy",
    "Comedy", "Stand-Up Comedy", "Sketch Comedy", "Improv", "Parody", "Satire", "Pranks", "Roast", "Meme Compilations",
    "News", "World News", "Politics", "Local News", "Tech News", "Science News", "Business News", "Weather Updates",
    "Entertainment", "Movie Trailers", "Film Reviews", "TV Show Reviews", "Celebrity Interviews", "Award Shows", "Trailers & Teasers",
    "Travel", "City Guides", "Travel Vlogs", "Hostel Tours", "Luxury Travel", "Backpacking", "Road Trips", "Train Journeys", "Hidden Gems", "Cultural Experiences",
    "Food", "Cooking Tutorials", "Baking", "Molecular Gastronomy", "Vegan Cooking", "Vegetarian Recipes", "BBQ & Grill", "Street Food", "Food Reviews", "Mukbang",
    "DIY & Crafts", "Woodworking", "Metalworking", "3D Printing", "Sewing & Knitting", "Crochet", "Embroidery", "Origami", "Pottery", "Calligraphy",
    "Science & Technology", "Gadget Reviews", "Product Teardowns", "Tech Tutorials", "Space Exploration", "Robotics", "Green Technology", "Blockchain & Crypto",
    "Health & Fitness", "Nutrition Tips", "Workout Routines", "Home Workouts", "Running Guides", "Weightlifting", "Meditation", "Mental Health",
    "Beauty & Fashion", "Makeup Tutorials", "Skincare Routine", "Haircare", "Fashion Hauls", "Style Tips", "Outfit Ideas", "DIY Fashion",
    "Animals", "Wildlife", "Pets", "Animal Rescue", "Aquatic Life", "Bird Watching",
    "Movies & Animation", "Short Films", "Animation", "Anime Reviews", "Storyboard Tutorials",
    "Photography & Art", "Landscape Photography", "Portrait Photography", "Street Photography", "Editing Tutorials", "Drawing Tutorials", "Digital Art",
    "Business & Finance", "Startup Advice", "Marketing Tips", "Personal Finance", "Budgeting", "Investing", "Real Estate Tips", "Career Development",
    "Lifestyle", "Minimalism", "Van Life", "Tiny House", "Home Decor", "Gardening", "Interior Design",
    "Vlogs & People", "Daily Vlogs", "Storytime", "Challenges", "Q&A", "Meetups",
    "Religion & Spirituality", "Christianity", "Buddhism", "Yoga Philosophy", "Astrology", "Mindfulness", "Meditation Guides",
    "Automotive", "Car Reviews", "Motorsport", "DIY Car Repair", "EV Reviews", "Motorcycle Vlogs",
    "Environment & Nature", "Climate Change", "Conservation", "Wildlife Documentaries", "Eco-Living",
    "Parenting & Family", "Pregnancy Tips", "Baby Care", "Parenting Hacks", "Family Vlogs",
    "Career & Jobs", "Resume Tips", "Interview Prep", "Remote Work", "Freelancing",
    "Relationships", "Dating Advice", "Marriage Tips", "Friendship Discussions",
    "Self-Improvement", "Motivational Talks", "Time Management", "Goal Setting", "Productivity Hacks",
]
